/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.45
 * Generated at: 2017-09-02 14:31:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class userForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/Administrator/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("file:/C:/Users/Administrator/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar", Long.valueOf(1502936911994L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort()
			+ path + "/";

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<base href=\"");
      out.print(basePath);
      out.write("\" />\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-1.9.1.min.js\"></script>\r\n");
      out.write("<title>userInfo</title>\r\n");
      out.write("\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"");
      out.print(path );
      out.write("/css/style.css\">\r\n");
      out.write("    <!--引入jQuery框架库文件-->\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("     <script type=\"text/javascript\" src=\"");
      out.print(path );
      out.write("/js/common.js\"></script>\r\n");
      out.write("      <script type=\"text/javascript\">\r\n");
      out.write("        window.onload = function () {\r\n");
      out.write("            var formElements = document.getElementsByTagName(\"form\")[0].elements;\r\n");
      out.write("\r\n");
      out.write("            for (var i = 0; i < formElements.length; i++) {\r\n");
      out.write("                formElements[i].oninput = function (event) {\r\n");
      out.write("                    event.target.setCustomValidity(\"\");\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        };\r\n");
      out.write("\r\n");
      out.write("        function checkInput(form) {\r\n");
      out.write("            var formElements = form.elements;\r\n");
      out.write("            var password = formElements.password;\r\n");
      out.write("            var confirmPassword = formElements.confirmPassword;\r\n");
      out.write("            \r\n");
      out.write("            if (password.value != confirmPassword.value) {\r\n");
      out.write("                confirmPassword.setCustomValidity(\"确认密码与登录密码必须相同\");\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            alert(\"登录成功\");\r\n");
      out.write("            return true;\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"container\">\r\n");
      out.write("        <header class=\"header\">\r\n");
      out.write("            <div class=\"head_left\">\r\n");
      out.write("                用户管理系统\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"head_right\">\r\n");
      out.write("                <a href=\"#\">帮助</a>\r\n");
      out.write("                <a href=\"#\">退出</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </header>\r\n");
      out.write("        <div class=\"left\">\r\n");
      out.write("            <div class=\"left_top\">\r\n");
      out.write("                <div> <a href=\"findUser\">用户查询</a></div>\r\n");
      out.write("                <div><a href=\"userForm.jsp\">用户新增</a></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"left_bottom\">\r\n");
      out.write("                <img src=\"images/login.png\" alt=\"加载失败\"> \r\n");
      out.write("                <span>当前登录用户</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"right\">\r\n");
      out.write("            <header class=\"right_head\">\r\n");
      out.write("                <h5>新增&编辑用户信息</h5>\r\n");
      out.write("            </header>\r\n");
      out.write("            <div class=\"right_content\">\r\n");
      out.write("            ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("               \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /userForm.jsp(74,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${update_user==null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("             <form action=\"addUser\" method=\"post\" onsubmit=\"return checkInput(this)\">\r\n");
          out.write("\r\n");
          out.write("                    <div class=\"input-group\">\r\n");
          out.write("                        <label class=\"input-label\">用户名称：</label>\r\n");
          out.write("                        <label class=\"input-content\">\r\n");
          out.write("                            <input class=\"input\" type=\"text\" name=\"user.name\" placeholder=\"请输入您的用户名！\"  minlength=\"2\"  maxlength=\"20\" autofocus=\"true\" required>\r\n");
          out.write("                            <span></span>\r\n");
          out.write("                        </label>\r\n");
          out.write("                    </div>\r\n");
          out.write("                    <div class=\"input-group\">\r\n");
          out.write("                        <label class=\"input-label\">登陆密码：</label>\r\n");
          out.write("                        <label class=\"input-content\">\r\n");
          out.write("                            <input class=\"input\" type=\"password\" name=\"user.password\" placeholder=\"请输入您的密码\"  minlength=\"6\" maxlength=\"20\" required>\r\n");
          out.write("                            <span></span>\r\n");
          out.write("                        </label>\r\n");
          out.write("                    </div>\r\n");
          out.write("                    <div class=\"input-group\">\r\n");
          out.write("                        <label class=\"input-label\">重复密码：</label>\r\n");
          out.write("                        <label class=\"input-content\">\r\n");
          out.write("                           <input class=\"input\" type=\"password\" name=\"user.passwordAgain\" placeholder=\"请输入您的确认密码\"  minlength=\"6\" maxlength=\"20\" required>\r\n");
          out.write("                            <span></span>\r\n");
          out.write("                        </label>\r\n");
          out.write("                    </div>\r\n");
          out.write("                    <div class=\"input-group\">\r\n");
          out.write("                        <label class=\"input-label\">电子邮箱：</label>\r\n");
          out.write("                        <label class=\"input-content\">\r\n");
          out.write("                           <input class=\"input\" type=\"email\" name=\"user.email\" placeholder=\"请输入您的邮箱\"  required>\r\n");
          out.write("                            <span></span>\r\n");
          out.write("                        </label>\r\n");
          out.write("                    </div>\r\n");
          out.write("                    <div class=\"input-group\">\r\n");
          out.write("                        <label class=\"input-label\">性 　 别：</label>\r\n");
          out.write("                        <label class=\"input-content\">\r\n");
          out.write("                        <input type=\"radio\" name=\"user.gender\" value=\"male\" checked>男\r\n");
          out.write("                        　　\t\t\t\t<input type=\"radio\" name=\"user.gender\" value=\"female\">女\r\n");
          out.write("                           \r\n");
          out.write("                        </label>\r\n");
          out.write("                    </div>\r\n");
          out.write("                    <div class=\"button-group\">\r\n");
          out.write("                        <button>保存</button>\r\n");
          out.write("                        <button type=\"reset\">重置</button>\r\n");
          out.write("                        <button type=\"button\">返回</button>\r\n");
          out.write("                    </div>\r\n");
          out.write("                </form>\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /userForm.jsp(120,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${update_user !=null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("             <form action=\"updateResultUser\" method=\"post\" onsubmit=\"return checkInput(this)\">\r\n");
          out.write("\r\n");
          out.write("                    <div class=\"input-group\">\r\n");
          out.write("                        <label class=\"input-label\">用户名称：</label>\r\n");
          out.write("                        <label class=\"input-content\">\r\n");
          out.write("                            <input class=\"input\" type=\"text\" name=\"user.name\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${update_user.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" placeholder=\"请输入您的用户名！\"  minlength=\"2\"  maxlength=\"20\" autofocus=\"true\" required>\r\n");
          out.write("                            <span></span>\r\n");
          out.write("                        </label>\r\n");
          out.write("                    </div>\r\n");
          out.write("                    <div class=\"input-group\">\r\n");
          out.write("                        <label class=\"input-label\">登陆密码：</label>\r\n");
          out.write("                        <label class=\"input-content\">\r\n");
          out.write("                            <input class=\"input\" type=\"password\" name=\"user.password\" value=\"update_user.password\" placeholder=\"请输入您的密码\"  minlength=\"6\" maxlength=\"20\" required>\r\n");
          out.write("                            <span></span>\r\n");
          out.write("                        </label>\r\n");
          out.write("                    </div>\r\n");
          out.write("                   \r\n");
          out.write("                    <div class=\"input-group\">\r\n");
          out.write("                        <label class=\"input-label\">电子邮箱：</label>\r\n");
          out.write("                        <label class=\"input-content\">\r\n");
          out.write("                           <input class=\"input\" type=\"email\" name=\"user.email\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${update_user.email }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" placeholder=\"请输入您的邮箱\"  required>\r\n");
          out.write("                            <span></span>\r\n");
          out.write("                        </label>\r\n");
          out.write("                    </div>\r\n");
          out.write("                    <div class=\"input-group\">\r\n");
          out.write("                        <label class=\"input-label\">性 　 别：</label>\r\n");
          out.write("                        <label class=\"input-content\">\r\n");
          out.write("                        <input type=\"radio\" name=\"user.gender\" value=\"male\" checked>男\r\n");
          out.write("                        　　\t\t\t\t<input type=\"radio\" name=\"user.gender\" value=\"female\">女\r\n");
          out.write("                           \r\n");
          out.write("                        </label>\r\n");
          out.write("                    </div>\r\n");
          out.write("                    <div class=\"button-group\">\r\n");
          out.write("                        <button>保存</button>\r\n");
          out.write("                        <button type=\"reset\">重置</button>\r\n");
          out.write("                        <button type=\"button\">返回</button>\r\n");
          out.write("                    </div>\r\n");
          out.write("                </form>\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
